/*
 * Copyright 2018-2025 Pavel Castornii.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.techsenger.alpha.api.component;

import java.util.List;
import java.util.Set;

/**
 * Every component instance has one ComponentDescriptor instance. A descriptor is created for every component
 * and is deleted when component is undeployed.
 *
 * @author Pavel Castornii
 */
public interface ComponentDescriptor {

    /**
     * Returns the id of the component instance.
     * @return
     */
    Integer getId();

    /**
     * Returns the alias of the component instance. We can use running component by id or by alias. Id is generated by
     * platform, alias we can set when create component. Alias like id is unique inside framework. One alias
     * can belong only to one component.
     *
     * @return
     */
    String getAlias();

    /**
     * Returns a flag that indicates whether the component instance is activated.
     *
     * @return true if component is activated, otherwise false.
     */
    boolean isActivated();

    /**
     * Returns the descriptors of the parent components. If there is no parent returns empty list.
     * @return
     */
    List<ComponentDescriptor> getParents();

    /**
     * Returns a flag that indicates whether parent classloader was used when component layer was created.
     *
     * @return
     */
    boolean usesParentClassLoader();

    /**
     * Returns the descriptors of all ancestor components (nodes higher than a given node in the same lineage),
     * i.e. higher than the component of the passed  descriptor. JPMS module layer graph is a directed acyclic
     * graph (DAG).
     *
     * @return
     */
    Set<ComponentDescriptor> findAncestors();

    /**
     * Returns the descriptors of all descendant components (nodes below than a given node in the same lineage),
     * i.e. below than the component of the passed  descriptor. JPMS module layer graph is a directed acyclic
     * graph (DAG).
     *
     * @return
     */
    Set<ComponentDescriptor> findDescendants();

    /**
     * Returns component config.
     *
     * @return
     */
    ComponentConfig getConfig();
}
