/*
 * Copyright 2018-2025 Pavel Castornii.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.techsenger.alpha.core.api.component;

import java.util.List;

/**
 *
 * @author Pavel Castornii
 */
public interface ComponentDescriptorDto {

    /**
     * Returns the id of the component instance.
     * @return
     */
    Integer getId();

    /**
     * Returns the alias of the component instance. We can use running component by id or by alias. Id is generated by
     * platform, alias we can set when create component. Alias like id is unique inside framework. One alias
     * can belong only to one component.
     *
     * @return
     */
    String getAlias();

    /**
     * Returns a flag that indicates whether the component instance is activated.
     *
     * @return true if component is activated, otherwise false.
     */
    boolean isActivated();

    /**
     * Returns component config.
     *
     * @return
     */
    ComponentConfigDto getConfig();

    /**
     * Returns the descriptors of the parent components. If there is no parent returns empty list.
     * @return
     */
    List<? extends ComponentDescriptorDto> getParents();

    /**
     * Returns a flag that indicates whether parent classloader was used when component layer was created.
     *
     * @return
     */
    boolean isParentClassLoaderUsed();
}
